### ISSUE TITLE
Popper not popup-ing newly raised windows

### ISSUE THREAD

**Issue by MagicRB** [karthink/popper#2]
I've installed popper with
```elisp
(use-package popper
  :straight t
  :init
  (setq popper-reference-buffers
    '("\\*Messages\\*"
      "Output\\*$"
      help-mode
      compilation-mode))
  (popper-mode +1))
```
and when I press `C-h f`, to make a new buffer show up, it appears but on the side like without popper, it does have the little `POP` thing in the modeline, but nothing else. If I do `popple-toggle-latest` it disappears and then if I run that command again, it appears correctly this time, as a proper popup.

**Comment by karthink** [comment]
I did most of my testing with custom display-buffer rules and completely missed this. It wasn't just help, all initial display of popups was scuppered.

Should be fixed in b32abcb. Please test?

**Comment by MagicRB** [comment]
Yup, that fixes it, it still doesn't work for Org Export Dispatcher but I didn't expect it to since that even takes over keyboard input completely. You can close it if you don't wanna tackle the dispatcher

**Comment by karthink** [comment]
Yeah, you're not going to be able to use popper to toggle the windows of org commands that set a transient keymap (org-capture templates menu, org-agenda menu, etc). I'm also not sure why you would want to, since they go away when you press `C-g` or when you finish the command. In a sense they're like magit's transient menus.

If the issue is that you don't like where they show up (temporarily taking over your other windows) and would prefer they show up the way other popups do, you can fix that by defining variants or advising them to use `display-buffer`. For example:

```elisp
(defun my/org-export-dispatch (&optional arg)
  (interactive "P")
  (cl-letf (((symbol-function #'org-switch-to-buffer-other-window)
             (symbol-function #'display-buffer)))
    (org-export-dispatch arg)))

(define-key org-mode-map (kbd "C-c C-e") #'my/org-export-dispatch)
```
And add the string `"^\\*Org Export Dispatcher\\*$"` to `popper-reference-buffers`. Now it should show up as a popup.

Beyond hacks like this turning org-menus into popups is beyond the scope of popper. I'm closing this issue but feel free to ask if you need more help with tweaking org-mode window behavior.

**Comment by MagicRB** [comment]
Thanks for the explanation, I was just curious if popper could do it somehow, but I knew that those Org windows are really special. I appreciate the free explanation :P great package btw, definitely works better than popwin

**Comment by Compro-Prasad** [comment]
I guess it would be better to mention these scenarios on priority. This is because many people might come looking to popup shell buffers and this would be a turn off for them. At least same was for me.
